# Database configuration
database:
  # Type of database
  # Available types are:
  #
  #  Remote database servers (require connection configuration below):
  #   - MYSQL
  #   - MARIADB
  #   - POSTGRESQL
  #   - SQLSERVER (unstable, for testing purposes only)
  #
  #  File-based databases:
  #   - H2 (recommended)
  #   - SQLITE (not recommended)
  storage-type: H2

  # The database server hostname (IP address or DNS)
  # The default port of your database engine will be used when not specified
  # You can override it by specifying the host as "host:port"
  host: 127.0.0.1

  # Name of the database to connect to
  # It must already exists before starting the server
  database: minecraft

  # Database credentials
  username: root
  password: passroot

  # Size of the connection pool
  # Don't change it if you don't know what you are doing
  # More informations: https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing
  pool-size: 10

  # How frequently each connection will send a packet to the database in order
  #  to avoid it being dead
  # Must be below your database setting for maximum lifetime
  # Time is in milliseconds
  keepalive-time: 30000 # 30 seconds

  # Maximum time before a request performed by a connection will time out if
  #  the server did not responded
  # Time is in milliseconds
  connection-timeout: 5000 # 5 seconds

  # Maximum life time of a single connection before it is renewed
  # It differs from the keep alive setting as the connection will be destroyed
  #  and then recreated when it reached its maximum life time
  # Time is in milliseconds
  maximum-lifetime: 1200000 # 20 minutees

  # Prefix of all tables created by the plugin
  table-prefix: lottery_
