name: ${project.name}
version: ${project.version}
authors: [Zodiia]
softdepend: [Vault, PlaceholderAPI]
depend: [zApi]
main: me.zodiia.lottery.LotteryPlugin
api-version: 1.17
website: ${project.url}
libraries: []
#  - "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.10"
#  - "org.jetbrains.kotlin:kotlin-reflect:1.5.10"
#  - "org.jetbrains.kotlinx:kotlinx-serialization-json:1.2.1"
#  - "com.charleskorn.kaml:kaml:0.33.0"
#  - "com.h2database:h2:1.4.200"
#  - "mysql:mysql-connector-java:8.0.24"
#  - "org.mariadb.jdbc:mariadb-java-client:2.7.3"
#  - "org.postgresql:postgresql:42.2.20"
#  - "org.jetbrains.exposed:exposed-core:0.31.1"
#  - "org.jetbrains.exposed:exposed-jdbc:0.31.1"
#  - "org.jetbrains.exposed:exposed-dao:0.31.1"
#  - "com.zaxxer:HikariCP:4.0.3"
permissions:
  lottery.*:
    default: op
    children:
      lottery.buy: true
      lottery.buy.others: true
      lottery.info: true
      lottery.last: true
      lottery.reload: true
      lottery.draw: true
  lottery.base:
    default: true
  lottery.buy:
    default: op
  lottery.buy.others:
    default: op
  lottery.info:
    default: true
  lottery.last:
    default: true
  lottery.reload:
    default: op
